name: CI - Go

on:
  push:
    branches: [main]
    paths:
      - 'scitt-golang/**'
      - 'tests/interop/**'
      - '.github/workflows/ci-golang.yml'
  pull_request:
    branches: [main]
    paths:
      - 'scitt-golang/**'
      - 'tests/interop/**'
      - '.github/workflows/ci-golang.yml'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        go-version: ['1.21', '1.22']

    steps:
      - uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go-version }}

      - name: Build
        working-directory: ./scitt-golang
        run: go build -v ./...

      - name: Test
        working-directory: ./scitt-golang
        run: go test -v ./...
